server:
  port: 9001
spring:
  application:
    name: tensquare-base #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tensquare_base?characterEncoding=utf-8
    username: root
    password: root
  jpa:
    database: MySQL
    show-sql: true
  rabbitmq:
    host: 192.168.137.188
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true
